apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: devsuprueba
  name: devsuprueba-deployment
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: devsuprueba-app
  replicas: 1
  template:
    metadata:
      labels:
        app.kubernetes.io/name: devsuprueba-app
    spec:
      containers:
      - image: vidd1992/devsu:latest
        imagePullPolicy: Always
        name: devsuprueba-container
        ports:
        - containerPort: 8000
        env:
        - name: DATABASE_NAME
          value: "./dev.sqlite"
        - name: DATABASE_USER
          value: "user"
        - name: DATABASE_PASSWORD
          value: "password"
